### ISSUE TITLE
Move this project to attic

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway_bundlers#5]
Reasons:

1. I forgot it existed
2. Hasn't been touched in years
3. If users want the capability of deploying a notebook + KG in a docker container, they're better off writing a bundler extension (http://jupyter-notebook.readthedocs.io/en/stable/extending/bundler_extensions.html) that fits your specific workflow and infrastructure (e.g., does a docker build and push to Kubernetes).

Leaving open for a couple days for the few followers to comment before moving to attic.

**Comment by parente** [comment]
Going, going, gone. Moving to attic.

**Comment by parente** [comment]
@takluyver could you please grant me access in the jupyter-attic org in order to move this project?

**Comment by takluyver** [comment]
Sorry, I don't have the necessary permissions to add people to that org, it appears.

**Comment by parente** [comment]
Doh. Saw your name on the org. Everyone else is hidden. I'll go bug @rgbkrk or @minrk. Sorry for the bother.

**Comment by takluyver** [comment]
No problem. I think it's a bit daft that Github defaults to hiding all members of an organisation.

**Comment by rgbkrk** [comment]
I have now been bugged.

**Comment by rgbkrk** [comment]
I'll move it now.

**Comment by rgbkrk** [comment]
Nevermind, I'm not an owner on jupyter-attic either.

/cc @jamieshq -- can you make me an owner on the attic?

**Comment by parente** [comment]
Yay. Attic'ed. Thanks!
